namespace GDParser;

// ReSharper disable InconsistentNaming
public enum GdBuiltInType
{
    @void,
    @Variant,
    @AABB,
    @Array,
    @Basis,
    @bool,
    @Callable,
    @Color,
    @Dictionary,
    @float,
    @int,
    @NodePath,
    @Object,
    @PackedByteArray,
    @PackedColorArray,
    @PackedFloat32Array,
    @PackedFloat64Array,
    @PackedInt32Array,
    @PackedInt64Array,
    @PackedStringArray,
    @PackedVector2Array,
    @PackedVector3Array,
    @Plane,
    @Projection,
    @Quaternion,
    @Rect2,
    @Rect2i,
    @RID,
    @Signal,
    @String,
    @StringName,
    @Transform2D,
    @Transform3D,
    @Vector2,
    @Vector2i,
    @Vector3,
    @Vector3i,
    @Vector4,
    @Vector4i,
}
// ReSharper restore InconsistentNaming