name: Publish to Nuget
on:
  release:
    types:
      - published
env:
  NuGetDirectory: ${{ github.workspace}}/nuget
  Version: ${{ github.event.release.tag_name }}
  PackageFile: GDParser.${{ env.Version }}.nupkg
  
jobs:
  create_nuget:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Pack
      run: dotnet pack --configuration Release -p:PackageVersion=${{ env.Version }} --output ${{ env.NuGetDirectory }}
    
    - name: Install nuget validator
      run: dotnet tool update Meziantou.Framework.NuGetPackageValidation.Tool --global
        
    - name: Validate package
      run: meziantou.validate-nuget-package ${{ env.PackageFile }}
      
    - name: Publish NuGet package
      run: dotnet nuget push ${{ env.PackageFile }} --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
